---
- name: Install Google Chrome
  hosts: local
  become: yes
  vars:
    app_name: Google Chrome
    app_name_pretty: Google Chrome
    app_url: https://dl.google.com/chrome/mac/stable/CHFA/googlechrome.dmg
    installer_type: app
    install_method: dmg
    download_file_type: dmg
    mount_path: "/Volumes/Google Chrome"
  vars_files:
    - ../setup-vars.yaml
  roles: 
    - installer